# Generated by Django 5.2.15 on 2026-06-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_contribution_result_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledger',
            name='action_type',
            field=models.CharField(choices=[('register_bonus', '注册奖励'), ('profile_completion_bonus', '完善资料奖励'), ('project_participation_cost', '参与课题消耗'), ('project_completion_return', '课题结题返还'), ('transfer', '积分转赠'), ('task_deposit', '任务承诺'), ('task_reward', '任务奖励'), ('sponsor_pool', '项目资助池'), ('admin_adjust', '管理员调整')], max_length=40),
        ),
    ]
