# Generated by Django 5.2.15 on 2026-06-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=500)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('body_markdown', models.TextField(blank=True)),
                ('project_no', models.PositiveIntegerField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('draft', '草稿'), ('open_recruiting', '开放招募'), ('team_building', '组队中'), ('active', '进行中'), ('experimenting', '实验中'), ('writing', '写作中'), ('submitted', '投稿中'), ('published', '已发表'), ('paused', '暂停'), ('archived', '归档')], default='open_recruiting', max_length=32)),
                ('source_md_path', models.CharField(blank=True, db_index=True, max_length=500)),
                ('source_pdf_path', models.CharField(blank=True, max_length=500)),
                ('page_path', models.CharField(blank=True, max_length=500)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('llm_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('community_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('composite_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommended_journal', models.CharField(blank=True, max_length=160)),
                ('needed_roles', models.JSONField(blank=True, default=list)),
                ('score_dimensions', models.JSONField(blank=True, default=dict)),
                ('has_pdf', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-composite_score', '-llm_score', 'topic_id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tag')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', through='projects.ProjectTag', to='projects.tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.theme'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(blank=True, max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='projects_au_action_2097ce_idx'), models.Index(fields=['target_type', 'target_id'], name='projects_au_target__4640f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('markdown', 'Markdown'), ('pdf', 'PDF'), ('html', 'HTML'), ('other', '其他')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['doc_type'], name='projects_pr_doc_typ_60bcb6_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'doc_type', 'path'), name='unique_project_document')],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(blank=True, max_length=80)),
                ('required_role', models.CharField(blank=True, max_length=80)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('todo', '待认领'), ('claimed', '已认领'), ('in_progress', '进行中'), ('review', '待审核'), ('done', '已完成'), ('cancelled', '已取消')], default='todo', max_length=32)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('credit_deposit', models.IntegerField(default=0)),
                ('credit_reward', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'status'], name='projects_pr_project_4795b4_idx'), models.Index(fields=['assignee', 'status'], name='projects_pr_assigne_9e900c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='projecttag',
            constraint=models.UniqueConstraint(fields=('project', 'tag'), name='unique_project_tag'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['stage', 'is_public'], name='projects_pr_stage_058bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['theme', 'stage'], name='projects_pr_theme_i_1dc175_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['has_pdf'], name='projects_pr_has_pdf_61be64_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-composite_score'], name='projects_pr_composi_2220d7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-community_score'], name='projects_pr_communi_b72979_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-updated_at'], name='projects_pr_updated_bf89a6_idx'),
        ),
    ]
