# Generated by Django 5.2.15 on 2026-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='compliance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='data_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='evaluation_metrics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_outputs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='research_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_route',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='file_space',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
