# Generated by Django 5.2.15 on 2026-06-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_compliance_notes_project_data_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='数据集文件', max_length=80)),
                ('file_type', models.CharField(choices=[('dataset', '数据集文件'), ('data_dictionary', '数据字典'), ('annotation_guide', '标注规范'), ('ethics', '伦理合规材料'), ('model_artifact', '模型与实验资产'), ('dataset_meta', '数据说明'), ('link', '外部链接'), ('other', '其他')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('path', models.CharField(max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.theme')),
            ],
            options={
                'ordering': ['theme__sort_order', 'theme__name', 'sort_order', 'section', 'title'],
                'indexes': [models.Index(fields=['theme', 'section'], name='projects_th_theme_i_b2da50_idx'), models.Index(fields=['file_type'], name='projects_th_file_ty_0d34ce_idx'), models.Index(fields=['is_active'], name='projects_th_is_acti_e421cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('theme', 'path'), name='unique_theme_file_path')],
            },
        ),
    ]
