# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_themefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="stage",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("open_recruiting", "开放招募"),
                    ("team_building", "组队中"),
                    ("active", "进行中"),
                    ("experimenting", "实验中"),
                    ("writing", "写作中"),
                    ("submitted", "投稿中"),
                    ("published", "已发表"),
                    ("paused", "暂停"),
                    ("archived", "归档"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
