# Generated by Django 5.2.15 on 2026-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_minimal_project_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clinical_endpoint',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='existing_foundation',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
