# Generated by Django 5.2.15 on 2026-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_field_250_and_auto_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
