# Generated by Django 5.2.15 on 2026-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectdocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_progress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_venue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='team_requirements',
            field=models.TextField(blank=True),
        ),
    ]
