# Generated by Django 5.2.15 on 2026-06-12 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='error_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source',
            field=models.CharField(blank=True, default='api', max_length=80),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(blank=True, default='success', max_length=32),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='projects_au_request_d4d462_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['status'], name='projects_au_status_c6df16_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by', '-created_at'], name='projects_pr_created_879ec4_idx'),
        ),
    ]
