# Generated by Django 5.2.15 on 2026-06-17 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_theme_file_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('owner_admin', '课题所有者和管理员')], default='public', max_length=32),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document_kind',
            field=models.CharField(choices=[('detail', '课题主PDF'), ('supplement', '补充说明'), ('progress', '项目进度文档')], default='supplement', max_length=32),
        ),
        migrations.CreateModel(
            name='ProjectDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('visible', '可见'), ('hidden', '已隐藏'), ('deleted', '已删除')], default='visible', max_length=32)),
                ('moderation_reason', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_discussions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_project_discussions', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_project_discussions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.projectdiscussion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', 'status', '-created_at'], name='projects_pr_project_4448e9_idx'), models.Index(fields=['parent', 'status', 'created_at'], name='projects_pr_parent__08959b_idx'), models.Index(fields=['author', 'status'], name='projects_pr_author__01f1b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('stage', '阶段变化'), ('document', '文档'), ('note', '说明')], default='note', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.CharField(choices=[('public', '公开'), ('owner_admin', '课题所有者和管理员')], default='public', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_progress_entries', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to='projects.projectdocument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='projects.project')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['project', '-occurred_at'], name='projects_pr_project_d53144_idx'), models.Index(fields=['entry_type'], name='projects_pr_entry_t_508044_idx'), models.Index(fields=['visibility'], name='projects_pr_visibil_f19363_idx')],
            },
        ),
    ]
