# Generated by Django 5.2.15 on 2026-06-05 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClaimIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('leader', '认领项目负责人'), ('experiment', '认领实验'), ('literature', '认领文献整理'), ('data', '认领数据处理'), ('model', '认领模型实现'), ('writing', '认领论文写作'), ('medical_review', '认领医学审核')], max_length=40)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已拒绝'), ('recorded', '已记录'), ('withdrawn', '已撤回')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_intents', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_claim_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'claim_type', 'status'], name='interaction_project_b72abe_idx'), models.Index(fields=['user', '-updated_at'], name='interaction_user_id_b399dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'project', 'claim_type'), name='unique_project_claim_intent')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', '-created_at'], name='interaction_project_88a07f_idx'), models.Index(fields=['user', '-created_at'], name='interaction_user_id_904653_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='unique_project_follow')],
            },
        ),
        migrations.CreateModel(
            name='ProjectInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('医生', '医生'), ('学生', '学生'), ('Leader', 'Leader'), ('AI工程师', 'AI 工程师'), ('医学统计', '医学统计'), ('文献整理', '文献整理'), ('数据处理', '数据处理'), ('论文写作', '论文写作'), ('资助者', '资助者'), ('其他', '其他')], max_length=40)),
                ('available_hours_per_week', models.PositiveSmallIntegerField(default=0)),
                ('experience', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已拒绝'), ('recorded', '已记录'), ('withdrawn', '已撤回')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'role', 'status'], name='interaction_project_357f47_idx'), models.Index(fields=['user', '-updated_at'], name='interaction_user_id_566eb9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'project', 'role'), name='unique_project_interest_role')],
            },
        ),
        migrations.CreateModel(
            name='ProjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', '-updated_at'], name='interaction_project_b0f1e9_idx'), models.Index(fields=['user', '-updated_at'], name='interaction_user_id_09c804_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='unique_project_score')],
            },
        ),
        migrations.CreateModel(
            name='SponsorIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_type', models.CharField(choices=[('funding', '经费'), ('credits', '积分池'), ('compute', '算力'), ('data_budget', '数据整理预算'), ('label_budget', '标注预算'), ('expert', '专家咨询'), ('student_labor', '学生劳务'), ('publication_fee', '论文版面费'), ('other', '其他')], max_length=40)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已拒绝'), ('recorded', '已记录'), ('withdrawn', '已撤回')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_intents', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'sponsor_type', 'status'], name='interaction_project_1c4cc1_idx'), models.Index(fields=['user', '-updated_at'], name='interaction_user_id_b62241_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'project', 'sponsor_type'), name='unique_sponsor_intent')],
            },
        ),
    ]
