# Generated by Django 5.2.15 on 2026-06-18 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_interaction_status_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclaimintent',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectclaimintent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectclaimintent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_claim_intents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectinterest',
            name='authorship_intention',
            field=models.CharField(choices=[('no_interest', '对署名没有兴趣'), ('contribution', '普通参与，按贡献'), ('co_first_or_corresponding', '主要参与，共同一作/共同通讯'), ('first_non_primary_unit', '主要参与，一作非一单位可'), ('first_primary_unit', '主要参与，一作一单位')], default='contribution', max_length=64),
        ),
        migrations.AlterField(
            model_name='projectclaimintent',
            name='claim_type',
            field=models.CharField(choices=[('leader', '认领项目负责人'), ('paper_first_unit', '认领课题（论文第一单位）'), ('experiment', '认领实验'), ('literature', '认领文献整理'), ('data', '认领数据处理'), ('model', '认领模型实现'), ('writing', '认领论文写作'), ('medical_review', '认领医学审核')], max_length=40),
        ),
        migrations.AlterField(
            model_name='sponsorintent',
            name='sponsor_type',
            field=models.CharField(choices=[('funding', '经费'), ('credits', '积分池'), ('compute', '资助算力'), ('token', '资助 token'), ('labor_fee', '资助劳务费'), ('data_budget', '数据整理预算'), ('label_budget', '标注预算'), ('expert', '专家咨询'), ('student_labor', '学生劳务'), ('publication_fee', '论文版面费'), ('other', '其他')], max_length=40),
        ),
    ]
