# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_projectclaimintent_review_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinterest",
            name="role",
            field=models.CharField(
                choices=[
                    ("医生", "医生"),
                    ("学生", "学生"),
                    ("大学老师", "大学老师"),
                    ("Leader", "Leader"),
                    ("AI工程师", "AI 工程师"),
                    ("医学统计", "医学统计"),
                    ("文献整理", "文献整理"),
                    ("数据处理", "数据处理"),
                    ("论文写作", "论文写作"),
                    ("资助者", "资助者"),
                    ("其他", "其他"),
                ],
                max_length=40,
            ),
        ),
    ]
