# Generated by Django 5.2.15 on 2026-06-18 14:54

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def assert_no_duplicate_active_review_claim_slots(apps, schema_editor):
    ProjectClaimIntent = apps.get_model('interactions', 'ProjectClaimIntent')
    duplicates = list(
        ProjectClaimIntent.objects.filter(
            claim_type__in=['leader', 'paper_first_unit'],
            status__in=['pending', 'approved'],
        )
        .values('project_id', 'claim_type')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
        .order_by('project_id', 'claim_type')
    )
    if duplicates:
        details = ', '.join(
            f"project_id={item['project_id']} claim_type={item['claim_type']} active_count={item['count']}"
            for item in duplicates[:20]
        )
        raise RuntimeError(
            'Duplicate active leader or paper_first_unit claim slots must be resolved before applying '
            f'unique_active_review_claim_slot. {details}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_add_teacher_participation_role'),
        ('projects', '0015_projectdocument_uploaded_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclaimintent',
            name='claimed_unit_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(assert_no_duplicate_active_review_claim_slots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='projectclaimintent',
            constraint=models.UniqueConstraint(condition=models.Q(('claim_type__in', ['leader', 'paper_first_unit']), ('status__in', ['pending', 'approved'])), fields=('project', 'claim_type'), name='unique_active_review_claim_slot'),
        ),
    ]
