# Generated by Codex on 2026-06-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0005_projectclaimintent_claimed_unit_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorintent",
            name="review_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sponsorintent",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sponsorintent",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_sponsor_intents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
