# Generated by Django 5.2.15 on 2026-06-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('real_name', models.CharField(blank=True, max_length=80)),
                ('role_type', models.CharField(choices=[('doctor', '医生'), ('student', '学生'), ('teacher', '老师'), ('ai_engineer', 'AI 工程师'), ('statistician', '医学统计'), ('sponsor', '资助者'), ('other', '其他')], default='other', max_length=32)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('research_interests', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('available_hours_per_week', models.PositiveSmallIntegerField(default=0)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_wechat', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('credit_balance', models.IntegerField(default=100)),
                ('reputation_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['role_type'], name='accounts_us_role_ty_42a6a3_idx'), models.Index(fields=['credit_balance'], name='accounts_us_credit__194afc_idx')],
            },
        ),
    ]
