# Generated by Django 5.2.15 on 2026-06-07 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ROLE_UID_PREFIXES = {
    "student": "S",
    "doctor": "D",
    "teacher": "T",
    "ai_engineer": "E",
    "statistician": "M",
    "sponsor": "F",
    "other": "U",
}


def backfill_profiles(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    User = apps.get_model("auth", "User")
    admin_username = getattr(settings, "OPENMEDAILAB_PLATFORM_ADMIN_USERNAME", "platform_admin")
    seen_emails = set()
    for profile in UserProfile.objects.select_related("user").order_by("user_id"):
        user = profile.user
        if user.is_staff and user.is_superuser and user.username == admin_username:
            profile.uid = "ADM00000001"
        else:
            prefix = ROLE_UID_PREFIXES.get(profile.role_type or "other", "U")
            profile.uid = f"{prefix}{user.id:08d}"
        normalized = (user.email or profile.contact_email or "").strip().lower()
        if normalized and normalized not in seen_emails:
            profile.email_normalized = normalized
            seen_emails.add(normalized)
        else:
            profile.email_normalized = None
        profile.save(update_fields=["uid", "email_normalized"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_normalized',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(backfill_profiles, noop_reverse),
        migrations.CreateModel(
            name='AccountToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('purpose', models.CharField(choices=[('email_verification', '邮箱验证'), ('password_reset', '密码重置')], max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', 'token_hash'], name='accounts_ac_purpose_5f0af2_idx'), models.Index(fields=['user', 'purpose', 'used_at'], name='accounts_ac_user_id_b79cf3_idx'), models.Index(fields=['expires_at'], name='accounts_ac_expires_c6ddfb_idx')],
            },
        ),
    ]
