# Generated by Codex on 2026-06-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_must_change_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email_verified_at",
        ),
        migrations.DeleteModel(
            name="AccountToken",
        ),
    ]
