# Generated by Django 5.2.15 on 2026-06-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role_type',
            field=models.CharField(choices=[('doctor', '医生'), ('undergrad_or_below', '在读本科及以下'), ('master_student', '在读硕士'), ('phd_student', '在读博士'), ('phd_or_above', '博士毕业及以上'), ('engineer', '工程师'), ('other', '其他')], default='other', max_length=32),
        ),
    ]
